### ISSUE TITLE
The build task is broken in master / 5.0.1-pre3.

### ISSUE THREAD

**Issue by meganwalker-ibm** [elastic/kibana-plugin-helpers#12]
I suspect the recent refactoring in this task has caused some issues.

- main() isn't being invoked when the build task is executed.
- The buildId variable isn't declared in the build() signature, meaning all the arguments passed in are misassigned.

**Comment by Kikketer** [comment]
I've put in a pull request: https://github.com/elastic/kibana-plugin-helpers/pull/15
I added a modification to the if check you had @meganwalker-ibm because mine had no dependencies at all.

The build function had the wrong parameters sent in and the `main()` function is simply called at the end.

**Comment by meganwalker-ibm** [comment]
Closing as fixes merged.

**Comment by spalger** [comment]
Thanks @meganwalker-ibm  and @Kikketer 

Just released `v5.0.1` with these fixes.
