### ISSUE TITLE
build_action expects callback

### ISSUE THREAD

**Issue by Kikketer** [elastic/kibana-plugin-helpers#16]
The `build_action.js` file is now taking a second parameter as a callback.  However the `run.js` that is calling it is doing an apply with the plugin and any other items from the Command library.
This results in having (plugin, command) being sent to that function and then throws a fit when the callback function (which was sent this command object) isn't a function.

I propose just using call in `run.js` (line 8):

```
action.call(null, idPlugin());
```

And if need-be a callback there, but not sure what purpose that would serve.

**Comment by spalger** [comment]
dammit, I knew that was a mistake. It was late

**Comment by Kikketer** [comment]
Haha you throw code like I do ;)
I'd do a pull but I'm still waiting on the compliance department to get back to me.

**Comment by spalger** [comment]
No worries, just released `v5.0.1-patch1` which should resolve the issue. This project will eventually get to the point where it's more stable and more widely used, but it's not there yet 😄
