### ISSUE TITLE
Key must be a buffer Error when installing plugins

### ISSUE THREAD

**Issue by Kikketer** [elastic/kibana-plugin-helpers#17]
I'm not sure if this is a plugin-helper issue or not.  But when I package up my plugins and attempt to install them I get the following error:

```
Transferring 6792164 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Plugin installation was unsuccessful due to error "Key must be a buffer"
```

I'm debugging now, but right now it appears to be happening somewhere in the `await kbnServer.ready();` in `cli_plugin/kibana.js` line 47.

**Comment by spalger** [comment]
@Kikketer Did you track this down? What version of node are you using?

On the kibana team we kind of take for granted that most people have [nvm](https://github.com/creationix/nvm) and [node-avn](https://github.com/wbyoung/avn) installed, so when they start working in a project the correct node-version is selected. I'll add this file to the plugin generation output, but if you aren't already be sure to use the same node version [that kibana requires](https://github.com/elastic/kibana/blob/master/.node-version)

**Comment by Kikketer** [comment]
I sort of did.  I had a couple plugins that I was developing set up as symlinks in the /plugins directory (mostly so I can demo having all of them in kibana at the same time).  I removed these symlinks and attempted the x-pack install and it worked.

The fact that they are symlinks may not be the issue, it may just be "there are others here" or something.

If you want to repeat the issue, have a plugin along side kibana, make a symlink in the /plugins directory that points to that plugin folder.  Then attempt to do the `./bin/kibana-plugin install x-pack`

**Comment by spalger** [comment]
Hmm, didn't happen when I symlinked a barebones generated plugin.

The only code I could find that produces a `"Key must be a buffer"` error is in node's crypto library. Any chance one of your plugins is doing some work outside of it's `init()` function?

**Comment by Kikketer** [comment]
So I double checked and narrowed it down to one plugin, my feedback plugin.

``` javascript
import feedbackRoute from './server/routes/feedback';

export default function (kibana) {
  return new kibana.Plugin({
    uiExports: {
      hacks: [
        'plugins/feedback-plugin/public/feedback'
      ]
    },

    config(Joi) {
      return Joi.object({
        enabled: Joi.boolean().default(true),
      }).default();
    },


    init(server, options) {
      // Add server routes and initalize the plugin here
      feedbackRoute(server);
    }


  });
};
```

It doesn't look too crazy.  The feedback plugin uses `request` and `emailjs` dependencies.  I can narrow the issue down further and let you know.

**Comment by spalger** [comment]
Cool, thanks looking into it.

I suspect somewhere in the dependency tree code is executing by virtue of being imported, rather than waiting to be called by `init()`. If you want to easily prevent that just convert your import of `feedbackRoute` to be a require statement within your `init()` function.

**Comment by Kikketer** [comment]
You called it, I had some configuration files brought in that did some messing with crypto.
After some messing to narrow it down, I did find another issue.  I'll put in a new ticket for it (and have a plugin that you can clone to perhaps see what the deal is).

To fix this issue I changed the above code to have:

``` javascript
    init(server, options) {
      // Add server routes and initalize the plugin here
      require('./server/routes/feedback')(server);
    }
```

It was just easier to move it in like that than to alter the config stuff.  Unfortunately I have to use `require` since things yell at me for attempting `import` inside that function.

I'll create the other issue once I get the example plugin put up in github.
