### ISSUE TITLE
Terminal doesn't recover after cmd-c

### ISSUE THREAD

**Issue by Kikketer** [elastic/kibana-plugin-helpers#19]
This is a minor issue.  When I run `npm run start` inside a plugin (runs `plugin-helpers start`) and then I do a `cmd-c` to stop it awhile later.  Anything I type into the terminal no longer appears.

I noticed that when I run `npm run start` in kibana and the same `cmd-c` it doesn't have this issue.  Not sure if it's just a simple update of a dependency.  I assume it's something related to the logger stopping normal output in the terminal.

**Comment by spalger** [comment]
Hmm, super strange. Hopefully that fixes it
