### ISSUE TITLE
kibana 5.x does not accept zip packages created by build-task

### ISSUE THREAD

**Issue by mkoertgen** [elastic/kibana-plugin-helpers#3]
For Kibana 5.x the zip package structure for plugins has changed. It seems that
- plugins need to be nested in an additional `kibana` folder
- plugin version must match the kibana version (indicated by `kibanas`-array ?)

**Comment by mkoertgen** [comment]
Nesting into `kibana` was simple, cf. commit https://github.com/spalger/kibana-plugin-helpers/pull/4/commits/309fa894e8d912a0a31038dab77a1e4137f535f2

Not sure how to approach the `kibanas`-versioning and preserving backwards compatibilty to 4.x

**Comment by mkoertgen** [comment]
The timelion-plugin builds additional packages one for each supported kibana version, cf.:

https://github.com/elastic/timelion/blob/master/gulpfile.js#L165

**Comment by Kikketer** [comment]
So I found that just nesting it in `kibana` also doesn't work.  It must be nested `kibana/name-of-plugin/`.
With that configuration, I have another issue:

```
Retrieving metadata from plugin archive
Error: Cannot find module '/Users/***/Documents/htdocs/kibana/plugins/.plugin.installing/kibana/name-of-plugin/package.json'
Plugin installation was unsuccessful due to error "Error retrieving metadata from plugin archive"
```

=== Later that day ===
I reduced the install steps down to simple extract (and kept the `.plugin.installing` folder to see what was happening).  It seems that the only file that ends up in my `.plugin.installing` folder is a file called `archive.part`

Strange, but I'm investigating further to see if it's an issue with @BigFunger

**Comment by mkoertgen** [comment]
The nesting issue was fixed with this commit (but not yet merged i think) https://github.com/elastic/kibana-plugin-helpers/pull/4/commits/309fa894e8d912a0a31038dab77a1e4137f535f2

For the metadata issue it is important that your plugin version matches the kibana version.

The resulting zip should be placed in the `build` directory.

**Comment by spalger** [comment]
It was applied in https://github.com/elastic/kibana-plugin-helpers/commit/0a0f5fea0a3f95529ab37c7eb4ae2440f5a85785, so this should be fixed. Thanks @mkoertgen!
