### ISSUE TITLE
get empty page when double click the plugin menu in sidebar

### ISSUE THREAD

**Issue by xycloud** [elastic/kibana-plugin-helpers#32]
I use ```yo kibana-plugin``` to init a plugin, and write something,
well , I get empty page when double click the plugin menu in sidebar

**Comment by spalger** [comment]
Hmm, I just tried it and things worked fine. Is your [Kibana development environment](https://github.com/elastic/kibana/blob/master/CONTRIBUTING.md#setting-up-your-development-environment) completely setup and up to date?

**Comment by xycloud** [comment]
sure, I found someone meet a same question with me: https://discuss.elastic.co/t/got-empty-page-when-i-click-plugin-menu-when-its-page-is-already-loaded/76578/6

**Comment by w33ble** [comment]
Closing for lack of feedback. If you find more details, feel free to open a new issue, or perhaps open an issue on the kibana repo.
