### ISSUE TITLE
can not install with node less than 6.0

### ISSUE THREAD

**Issue by callmewhy** [elastic/kibana-plugin-helpers#33]
Hi, I run npm install in my project and get a npm error: 

```
enable_collecting_unknown_options.js:6
    let opts = origParse.call(this, argv);
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

then I look into the src:

https://github.com/elastic/kibana-plugin-helpers/blob/master/lib/enable_collecting_unknown_options.js#L6

maybe should use `const` instead of `let`?

**Comment by w33ble** [comment]
`const` wouldn't work either, according to the error. That needs to be changed to a `var`.

**Comment by spalger** [comment]
What version of kibana are you developing against? Even 4.x requires node 6
