### ISSUE TITLE
Test tasks fail when running on a windows environment

### ISSUE THREAD

**Issue by suvlite** [elastic/kibana-plugin-helpers#36]
Running the test:browser and test:server tasks will fail on a windows environment with the following exception:
```
child_process.js:513
    throw err;
    ^

Error: spawnSync npm ENOENT
    at exports._errnoException (util.js:1022:11)
    at spawnSync (child_process.js:468:20)
    at execFileSync (child_process.js:505:13)
    at testBrowserAction (..
```

This seems to be an issue with how Node calls execFileSync. Changing the `cmd` variable from 'npm' to 'npm.cmd' in the actions:
```
  var cmd = 'npm';
  var args = ['run', 'test:dev', '--'].concat(kbnServerArgs);
  execFileSync(cmd, args, {
    cwd: plugin.kibanaRoot,
    stdio: 'inherit'
  })
```
fixes the issue.

**Comment by w33ble** [comment]
> This seems to be an issue with how Node calls execFileSync.

I'm guessing that's a Windows only thing. Do you have a reference to this issue that you could link to? Or maybe just explain how you got that solution? I'm hoping it will lead to a true cross-platform fix...

**Comment by spalger** [comment]
It's definitely a pretty common need: https://github.com/elastic/kibana/blob/d8d65526c6afba0e12cbc39fe844ec0a3fb9ba95/tasks/ui_framework.js#L15-L16

**Comment by w33ble** [comment]
Huh, news to me.

@suvlite you say both the browser and server tasks are failing, but you only included error output for the browser tests task. Is the server task failing for the same reason, and does using `mocha.cmd` instead fix the issue?

**Comment by suvlite** [comment]
@w33ble 
Yes, test:server also fails because of the same reason. Changing to mocha.cmd however does not fix it, I assume, because mocha is not installed globally. However passing the whole path worked:
`var cmd = '..\\kibana\\node_modules\\.bin\\mocha.cmd';`
