### ISSUE TITLE
Attempting Yarn when there isn't one

### ISSUE THREAD

**Issue by Kikketer** [elastic/kibana-plugin-helpers#40]
I discovered this issue when moving from version 6.0.2 to 6.0.3.
It seems my build process now suddenly thinks that I have a yarn.lock file and attempts to use yarn (which isn't installed).

With 6.0.3:
```
14-Apr-2017 15:36:34	> plugin-helpers build
14-Apr-2017 15:36:34	
14-Apr-2017 15:36:34	BUILD ACTION FAILED: { Error: spawnSync yarn ENOENT
14-Apr-2017 15:36:34	    at exports._errnoException (util.js:1012:11)
14-Apr-2017 15:36:34	    at spawnSync (child_process.js:453:20)
14-Apr-2017 15:36:34	    at execFileSync (child_process.js:490:13)
14-Apr-2017 15:36:34	    at /opt/lforge/atlassian_data/bamboo_home/xml-data/build-dir/ETSITOADA-DFP-ITR/node_modules/@elastic/plugin-helpers/tasks/build/create_build.js:51:9
14-Apr-2017 15:36:34	    at process._tickCallback (internal/process/next_tick.js:103:7)
14-Apr-2017 15:36:34	  code: 'ENOENT',
14-Apr-2017 15:36:34	  errno: 'ENOENT',
14-Apr-2017 15:36:34	  syscall: 'spawnSync yarn',
14-Apr-2017 15:36:34	  path: 'yarn',
14-Apr-2017 15:36:34	  spawnargs: [ 'install', '--production', '--no-bin-links' ],
14-Apr-2017 15:36:34	  file: 'yarn',
14-Apr-2017 15:36:34	  args: [ 'yarn', 'install', '--production', '--no-bin-links' ],
14-Apr-2017 15:36:34	  options: 
```

With 6.0.2 everything works fine.  I checked out your code at https://github.com/elastic/kibana-plugin-helpers/blob/master/tasks/build/create_build.js#L45 and it seems like it would work (in saying there's no yarn.lock file).  I'm not sure exactly what it's doing to think that the lock file exists.

**Comment by w33ble** [comment]
Upgrade to 6.0.4. 6.0.3 is indeed broken.

**Comment by w33ble** [comment]
For reference, it was fixed in https://github.com/elastic/kibana-plugin-helpers/commit/d48808f8d832bda1dd11f84724958ad78e08aa0e
