### ISSUE TITLE
Configurable build source patterns

### ISSUE THREAD

**Issue by jbudz** [elastic/kibana-plugin-helpers#46]
Filing from https://github.com/elastic/kibana/issues/8870.

In some cases it may be useful to include more files in a build than https://github.com/elastic/kibana-plugin-helpers/blob/master/lib/plugin_config.js#L12.  The ability to configure build patterns would help solve this.

**Comment by w33ble** [comment]
This already exists. See https://github.com/elastic/kibana/issues/8870#issuecomment-324392757

TL;DR - Include your own list of files using the `buildSourcePatterns` in a `.kibana-plugin-helpers.json` you drop in your plugin root.

**Comment by jbudz** [comment]
Nice, thanks @w33ble and for the followup in the other thread too.

**Comment by w33ble** [comment]
No problem, thanks for making it easy by linking back :)

FYI, Any of those values can be overridden from the config file. The list you noted are just the defaults, the config file settings [supersede all those](https://github.com/elastic/kibana-plugin-helpers/blob/master/lib/plugin_config.js#L33).
