### ISSUE TITLE
.kibana-plugin-helpers.json ignored if it has a syntax error

### ISSUE THREAD

**Issue by spalger** [elastic/kibana-plugin-helpers#64]
We should log an error and fail if we find a `.kibana-plugin-helpers.json` file that is invalid rather than ignoring it and moving on.

**Comment by kimjoar** [comment]
Good catch! We should maybe have an `ENOENT` check in https://github.com/elastic/kibana-plugin-helpers/blob/3511054dfb57f33d156250c26f016c430fcce83d/lib/config_file.js#L22
