### ISSUE TITLE
start plugin

### ISSUE THREAD

**Issue by ytzlax** [elastic/kibana-plugin-helpers#7]
Hi,
I using windows, so when I want to start my plugin I typing:
"./bin/kibana --dev --plugin-path=../path/to/first_plugin"
and I get the next error:
"FATAL Error: Config schema already has key: first_plugin",

someone can help?

thanks

**Comment by spalger** [comment]
Do you already have a copy of the first_plugin in kibana's `plugins` directory? This usually means that two copies of the plugin are being included in Kibana

**Comment by ytzlax** [comment]
I already have, where I supposed to store the plugin?
I thought that I need to store the plugin in kibana plugin directory,
And from there start the plugin,
Am I wrong?

Thanks

**Comment by spalger** [comment]
Actually you should put your plugin code in it's own directory. When you run `npm start` from that directory it will start kibana and include your plugin temporarily.

**Comment by spalger** [comment]
If you want to develop your code from within Kibana, you can absolutely do that too, but you don't need `npm start` in that case. Just start kibana like you normally would

**Comment by spalger** [comment]
Closing this due to lack of feedback, feel free to reopen if this is still an issue.

**Comment by ytzlax** [comment]
Thanks
