### ISSUE TITLE
Can't test plugin

### ISSUE THREAD

**Issue by pjhampton** [elastic/kibana-plugin-helpers#74]
Hey,

I'm having a really tough time running the tests via the kibana plugin helpers for the [kibana-prometheus-exporter](https://github.com/pjhampton/kibana-prometheus-exporter):

```
➜  kibana-prometheus-exporter git:(release/6.4.0) npm run test:server

> kibana-prometheus-exporter@1.0.0 test:server /Users/pjh/Desktop/es660/kibana/kibana-6.6.0-darwin-x86_64/plugins/kibana-prometheus-exporter
> plugin-helpers test:server

child_process.js:658
    throw err;
    ^

Error: spawnSync /Users/pjh/Desktop/es660/kibana/kibana-6.6.0-darwin-x86_64/plugins/kibana/node_modules/.bin/mocha ENOENT
    at Object.spawnSync (internal/child_process.js:998:20)
    at spawnSync (child_process.js:622:24)
    at execFileSync (child_process.js:650:13)
    at module.exports (/Users/pjh/Desktop/es660/kibana/kibana-6.6.0-darwin-x86_64/plugins/kibana-prometheus-exporter/node_modules/@elastic/plugin-helpers/tasks/test/server/test_server_action.js:22:3)
    at run (/Users/pjh/Desktop/es660/kibana/kibana-6.6.0-darwin-x86_64/plugins/kibana-prometheus-exporter/node_modules/@elastic/plugin-helpers/lib/run.js:9:10)
    at /Users/pjh/Desktop/es660/kibana/kibana-6.6.0-darwin-x86_64/plugins/kibana-prometheus-exporter/node_modules/@elastic/plugin-helpers/cli.js:75:5
    at Command.actionWrapper (/Users/pjh/Desktop/es660/kibana/kibana-6.6.0-darwin-x86_64/plugins/kibana-prometheus-exporter/node_modules/@elastic/plugin-helpers/cli.js:12:8)
    at Command.listener (/Users/pjh/Desktop/es660/kibana/kibana-6.6.0-darwin-x86_64/plugins/kibana-prometheus-exporter/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:197:13)
    at Command.parseArgs (/Users/pjh/Desktop/es660/kibana/kibana-6.6.0-darwin-x86_64/plugins/kibana-prometheus-exporter/node_modules/commander/index.js:651:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kibana-prometheus-exporter@1.0.0 test:server: `plugin-helpers test:server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kibana-prometheus-exporter@1.0.0 test:server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pjh/.npm/_logs/2019-02-14T15_27_41_342Z-debug.log
```

I want to start running these tests and building the artifact on the CircleCI rather than doing it all manually. Can anyone help with debugging this. The log mentioned at the end of the script isn't helpful at all - doesn't give any additional info.

**Comment by spalger** [comment]
Hmm, that error seems to imply you haven't installed the dependencies for Kibana

**Comment by pjhampton** [comment]
Sure - the **node_modules/** dir existed within kibana, and I ran `npm i` again. Still the seem issue. Any other suggestions? I really appreciate any ideas at this stage.

**Comment by spalger** [comment]
Can you share some reproduction steps so I can try to debug locally?

**Comment by pjhampton** [comment]
Yeah, for sure:

1. Download latest Kibana
2. `cd` into kibana/plugins
3. In terminal, `git clone https://github.com/pjhampton/kibana-prometheus-exporter.git`
4. `cd kibana-prometheus-exporter`
5. `npm i`
6. `npm run test:server`

**Comment by spalger** [comment]
So, around Kibana 6.3 we moved plugin-helper development into the main Kibana repository. Around that time we also added the `@kbn/pm` tool and required that Kibana plugins are developed outside the repository in a sibling `kibana-extra` directory. The setup is designed to use relative package imports for linking to the plugin-helpers and other Kibana dependencies via `link:../kibana/packages/xyx` dependency versions.

It's going to be a bit of a migration to get your plugin updated to follow those standards, and I'm not sure there is a migration guide that spells it out very clearly, but you might benefit from doing a couple things:
1. consider keeping different local checkouts for different major versions of your plugin. For kibana development I have a `~/kbn-dev` directory that looks like this:

   ```
    ~/kbn-dev
      master
        elasticsearch
        kibana
        kibana-extra
      7.x
        elasticsearch
        kibana
        kibana-extra
      7.0
        kibana
      6.7
        kibana
   ```

    I then can use a `kbn` script to switch between them, `kbn` takes me to `~/kbn-dev/master/kibana`, `kbn 6.7` takes me to `~/kbn-dev/6.7/master`, for instance.

    ```
    # loaded by my .bashrc file
    function kbn {
      cd "${HOME}/kbn-dev/${1:-master}/kibana" || return 1
    }
    ```

    This way you can have your plugin in different places based on how it need to integrate with the Kibana repository

2. it might be easier to move to the new style for plugins if you run the plugin generator in a 6.3+ instance of the Kibana repo, and then either look through the generated plugin or update it with the code from your existing plugin.

**Comment by spalger** [comment]
BTW, in the new plugin-helpers which are in the repo the `plugin-helpers` package is updated to work with Kibana 6.3+, which involves calling the `scripts/mocha` script in the Kibana repo with the necessary files from the plugins.

**Comment by pjhampton** [comment]
Great. Thanks 🙏
