### ISSUE TITLE
Question: Kibana Plugin releasing best practices

### ISSUE THREAD

**Issue by pjhampton** [elastic/kibana-plugin-helpers#75]
Hey @spalger 👋 Quick question 

I'm having a bit of a headache managing the releasing of my plugin for each version. So for example - if a bug is found in version 6.7.1, I need to add and re-release all the way back to 5.6.x, where each version is branch based. I haven't really maintained a project like this before - it's like maintaining 40 different projects. Do you have any tips or recommendations? 

Thanks! 😄

**Comment by spalger** [comment]
Hey @pjhampton, I understand the feeling. I don't personally have any experience with this sort of thing, but maybe you could try only supporting the latest versions of the 5.6/6.x/7.x versions.

On the Kibana team we have a branch for each minor version ([7.x](https://github.com/elastic/kibana/tree/7.x) for example), and we use https://www.npmjs.com/package/backport to create backport PRs for each change so we can apply the squashed PR commit to each minor version branch. Then we will release a new version of 7.x which from that branch.

If you did something similar with your plugin you could make it compatible with the most recent 7.x version of Kibana and encourage users to upgrade Kibana to the most recent 7.x version (which should be a non-breaking upgrade for users already using an older 7.x version).

**Comment by pjhampton** [comment]
Thanks so much, @spalger 🙇🙏 (as always). Backport looks like a good starting point for me
