### ISSUE TITLE
Build task does not include npm dependencies when there is only one

### ISSUE THREAD

**Issue by meganwalker-ibm** [elastic/kibana-plugin-helpers#8]
For some reason I can't get the build script to include a node module that is listed as a dependency in the generated zip.

Using kibana-plugin-generator@5.0.0 as a starting point for the plugin, and `material-design-icons` as an example I can reproduce this reliably with

```
mkdir test-plugin
cd test-plugin
yo kibana-plugin [accept defaults]
npm install --save material-design-icons
npm run build
```
If you then look in the zip that was generated the node_modules directory is not there, so the dependency wasn't packaged.

By annotating tasks/build/build_action.js with some logging (manually, and with the gulp-debug module) I can see the following
The `files` variable right before passing it into the vfs.src() is
```
["package.json","index.js","{lib,public,server,webpackShims}/**/*","node_modules/{material-design-icons}/**/*"]
```
So it's picked up that it should be including it.

But with gulp-debug I can see that the files that make it through into the stream are only 
```
[15:31:36] gulp-debug: package.json
[15:31:36] gulp-debug: index.js
[15:31:36] gulp-debug: public/app.js
[15:31:36] gulp-debug: public/hack.js
[15:31:36] gulp-debug: public/less
[15:31:36] gulp-debug: public/templates
[15:31:36] gulp-debug: server/routes
[15:31:36] gulp-debug: public/less/main.less
[15:31:36] gulp-debug: public/templates/index.html
[15:31:36] gulp-debug: server/routes/example.js
[15:31:36] gulp-debug: 10 items
```

So for some reason it's not finding the installed module, though it is there in the directory structure.

I'm at a loss to explain why it's not managing to match the directory. I'm not overly familiar with the globbing syntax so not sure if the bug lies in the constructed files array.

**Comment by meganwalker-ibm** [comment]
More digging shows that using a {list} with a single item will return no matches.
https://github.com/isaacs/node-glob/issues/92

Based on that it looks like the code needs to detect a dependency list of length 1, and not use the {list} format in that case.

**Comment by spalger** [comment]
Nice discovery, I'll get this fixed today
